### ISSUE TITLE
Any plans to support videos?

### ISSUE THREAD

**Issue by raRaRa** [andrieslouw/imagesweserv#126]
Just curious if there are any plans to support videos. Even just for caching purposes via CloudFlare. Well, I guess I could just register my own CloudFlare account for that purpose, but it has always confused me how much bandwidth can be cached without hitting some limits on their service.

Thanks!

**Comment by andrieslouw** [comment]
Support for videos is not on our roadmap unfortunately. It would simply cost too much processing power & bandwidth, and there are many great hosts for those already (this is also true for animated images). I'm also not entirely sure of the benefit of resizing/downsampling video-streams/animations on our end.

If I may suggest some (lesser-known) alternatives for video-hosting: [Vimeo](https://vimeo.com), [Wistia](https://wistia.com), [vzaar](https://vzaar.com), [Brightcove](https://www.brightcove.com), [SproutVideo](https://sproutvideo.com).

**Comment by danielbeeke** [comment]
In regard to this, have you thought about supporting the range header for videos? It would not need to download the whole video, if I understand correctly.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests.

**Comment by adamJLev** [comment]
Being able to grab the first frame of a mp4 video (e.g. thumbnail/poster) via weserv would be a really handy feature, probably not super simple to build but just throwing it out there 🙏🏼

like daniel said, can be done without downloading the full video, using a range header request as daniel mentions here - so that it stays fast and efficient.

thanks guys!
