### ISSUE TITLE
Relationship with Cloudfare?

### ISSUE THREAD

**Issue by fredguest** [andrieslouw/imagesweserv#127]
Hi! It says on `https://images.weserv.nl/` that "We're part of the Cloudflare community" but I was hoping you could elaborate on what that means exactly? Do you pay Cloudflare to use their CDN or do they provide you with free service? If you do pay Cloudflare, how do you support those costs without charging anything to use `https://images.weserv.nl/`? Also, do you have any kind of uptime guarantees between yourselves and Cloudflare? I hate to look a gift horse in the mouth because `https://images.weserv.nl/` seems like an amazing service, but I guess it seems too good to be true in a way :)

**Comment by andrieslouw** [comment]
We've started this service in 2007, used CloudFlare since early 2012, and are on the free-tier since 2015. Costs for the servers to support images.weserv.nl are really low. You can read more about that on [our wiki](https://github.com/andrieslouw/imagesweserv/wiki/About-this-service-and-why-it-is-free). CloudFlare is based on the same principles to provide their services, [as you can read here](https://www.cloudflare.com/cdn/).

Uptime guarantees buy you nothing but expensive insurance policies. We've had 99,993% uptime on average since 2007, all based on best-effort from all sides. Our service will not be the best fit for everyone: if you need more guarantees, anything besides best-effort, we encourage you to use our config and code as provided on this GitHub, and build your own solution. We're always happy to help with questions that may arise if you do so.

**Comment by fredguest** [comment]
Fair enough. Thanks for the explanation Andries. We're going to give it a shot and see how it goes 🙌🏼
