### ISSUE TITLE
Add Referer parameter

### ISSUE THREAD

**Issue by mrbl** [andrieslouw/imagesweserv#177]
Some sites check Header Referer and do not give the image  ("HTTP 403 Forbidden").
Example: https://images.weserv.nl/?url=example.com/example.jpg&h=300&referer=example.com

**Comment by marcselman** [comment]
We've seen this happen on some servers too.

**Comment by andrieslouw** [comment]
While [referer spoofing](https://en.wikipedia.org/wiki/Referer_spoofing) would be relatively easy to implement, I'm a bit reluctant to do so on the public service, because it would open the service to abuse, or as a way to bypass blocks. If you control the source of the image (which you should), it's easy to exclude our servers from referer-blocking. If the owner of the origin doesn't want its bandwidth to be used by other sites, it should be their choice.

In addition, passing user-supplied `referer=` could cause our service to be used for [referer spam](https://en.wikipedia.org/wiki/Referrer_spam). And if we would forward the `Referer:` supplied by the users browser when requesting images, it could break the [anonymity of our service](https://images.weserv.nl/faq/#are-you-passing-any-information-to-the-origin-server).

But feel free to use our source-code, and modify its behavior to your likening!

**Comment by marcselman** [comment]
I agree with your points. But you could just send a referer header with `images.weserv.nl` right? At the moment you are not sending any referer header and some servers don't like that.

**Comment by andrieslouw** [comment]
We would just be referer spamming ourselves in that case. Origins should fix their dependency on referers, there are lots of cases in which browsers omit the `Referer:` already, so it isn't reliable, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by kleisauke** [comment]
Closing for the reasons given above.
