### ISSUE TITLE
Is the API down?

### ISSUE THREAD

**Issue by raRaRa** [andrieslouw/imagesweserv#190]
I'm just seeing a Cloudflare error page. Something up? @andrieslouw @kleisauke (friendly poke)

**Comment by andrieslouw** [comment]
One of our servers seems to have issues, working on it.

**Comment by raRaRa** [comment]
Thanks for the super quick response @andrieslouw - much appreciated! <3

**Comment by raRaRa** [comment]
Everything looks fine to me now. Super fast'n smooth.

**Comment by andrieslouw** [comment]
Immediately took it out of the loadbalancers, but I am still working on the server itself, seems to have been some filesystem issues.

**Comment by andrieslouw** [comment]
**Found & fixed:** we recently (API 5) changed the location of some of the log-files, but forgot to exclude this new path from backups. 

**Issue:** Backup-server tried to backup the access-log of nginx (which was still being written to), which, after ~30 hours, caused the filesystem to limp into read-only mode. This caused nginx to hang because it couldn't read nor write to the logfile anymore. Issue was amplified because we gzip (all) logfiles on-the-fly, so the file needs to be read before writing any additions to it.

**Fix:** Excluded the path from backups, and removed all backups of this path (to comply with what is stated in the privacy-policy: max. 7 days of logging, only on server, no backups of logs).
