### ISSUE TITLE
Animated GIF? Convert to MP4 or WebM

### ISSUE THREAD

**Issue by hellojere** [andrieslouw/imagesweserv#193]
Thanks for the awesome service, and highly appreciate the animated GIF support on the version 5.

However, I would love to have support for converting animated GIF's to MP4, and possibly WebM, video formats. Can imagine this being computationally challenging, but hopefully, the saved bandwidth would be enough to justify it. 

This's currently the only feature why I still depend on Cloudinary.

**Comment by andrieslouw** [comment]
Will review this, I'm not sure if this is possible with the existing libraries. Thanks for the suggestion!

**Comment by andrieslouw** [comment]
This is a tough one; our libraries don't have MP4/WebM support, and many browsers don't like to load MP4 nor WebM when using `<img src="">` tags, so you'd need to use the `<video>` tag ([according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)), which means we cannot do this automatically for every animated GIF.

Also, modifying videos is a bit out of the comfort zone of our free service; I'd need to check on proper licensing to use H.264/H.265 for example, and WebM has some issues with patents.

I'll decline this issue for now, mainly because we are only equipped (servers, bandwidth, licenses, expertise) to handle images, not video. But if you know of a great open-sourced library, without any form of licensing (or patent issues), which can easily output videos, please let us know!

**Comment by kleisauke** [comment]
Closing as this is out-of-scope for now.
