### ISSUE TITLE
Self hosting (AWS) and Cloudflare?

### ISSUE THREAD

**Issue by RichardSieg** [andrieslouw/imagesweserv#200]
Hey there! We successfully host your really nice image service using AWS. We are wondering whether images are still sent to Cloudflare for caching or whether we have to do manually do this?

As a test, I deleted an image and our service still provided it. Could also be the nginx proxy caching be responsible for that?

Thanks for the clarification!

**Comment by andrieslouw** [comment]
Hi Richard,

Did you take a look at: https://images.weserv.nl/faq/#how-are-images-cached-by-your-servers

The domain images.weserv.nl is behind Cloudflare indeed. Depending on the amount of requests, they will keep it in cache for a while. If needed, I can provide the config we use for this?

**Comment by RichardSieg** [comment]
Hi Andries,

thanks for your answer. I read the FAQ. However, we are hosting the service on our own servers (AWS) and my question was, whether Cloudflare is still used in that case.

Thanks,

Richard

**Comment by raRaRa** [comment]
@RichardSieg You must setup Cloudflare yourself in order to utilize it in front of your self-hosted service.

HTTP request -> Cloudflare (respond here if it's cached on CF.) -> Your AWS service. So as you can see the request has to go through Cloudflare first and you need to configure your DNS records there, etc.

**Comment by andrieslouw** [comment]
@raRaRa is right, in that case you'll need to setup Cloudflare on your own.

**Comment by RichardSieg** [comment]
Thanks for clarifying!
