### ISSUE TITLE
How does you caching work?

### ISSUE THREAD

**Issue by PH4NTOMiki** [andrieslouw/imagesweserv#213]
I'm sorry for trouble, but I'm wondering if someone from Frankfurt, Germany request an image(from your service) and after 5 minutes someone from Zagreb, Croatia request that same image would there be need to contact origin server again or would you just load it from the cache on your servers(not from Cloudflare's obviously).
Thanks

**Comment by andrieslouw** [comment]
No trouble at all, it is partly explained here: https://images.weserv.nl/faq/#how-are-images-cached-by-your-servers

The flow is: Browser <- Cloudflare's nginx proxy_cache (31 days MRU, multiple POP's non-synced) <- Our nginx proxy_cache (7 days MRU, single POP) <- Our code <- Origin.

So the request will be cached shortly in RAM in our nginx proxy_cache, but Cloudflare needs to fetch it twice (once for every CDN location they have).

Due to how [MRU-caches work](https://en.wikipedia.org/wiki/Cache_replacement_policies#Most_recently_used_(MRU)), I can not guarantee the 7 days, nor can I guarantee the 31 days. If there's not much traffic on a resource, it could be expelled from cache within minutes instead of days.

**Comment by andrieslouw** [comment]
Hope this helped, please feel free to re-open if questions remain!
