### ISSUE TITLE
Feature request: WebP support detection

### ISSUE THREAD

**Issue by PH4NTOMiki** [andrieslouw/imagesweserv#214]
Hi, I was wondering would it be possible for you to add WebP detection on your service, like simple Accept header checking for image/webp in it because most of the browsers that actually support WebP also send "image/webp" in their HTTP Accept header and to put it under "output=webpdetect" URL parameter or something similar.
Thanks in advance

**Comment by andrieslouw** [comment]
Will need to check if this is possible, Cloudflare caching is based on URL, without checking request-headers from browsers.

**Comment by PH4NTOMiki** [comment]
Maybe you can use Vary http header somehow

**Comment by AnatolyUA** [comment]
afaik it won't work with Cloudflare free account, they will respect Vary only on Enterprise accounts. It is possible to use html5 srcset feature for your porposes:
```
<picture>
  <source srcset="img/awesomeWebPImage.webp" type="image/webp">
  <source srcset="img/creakyOldJPEG.jpg" type="image/jpeg"> 
  <img src="img/creakyOldJPEG.jpg" alt="Alt Text!">
</picture>
```
(more info: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images )

**Comment by andrieslouw** [comment]
As @AnatolyUA already explained (thanks!) this isn't possible with our current Cloudflare implementation, and it would also raise issues due to [the different caches involved](https://images.weserv.nl/faq/#how-are-images-cached-by-your-servers).

Please use the `<picture>`-tag as explained by @AnatolyUA (thanks again!).
