### ISSUE TITLE
Discord 403 errors?

### ISSUE THREAD

**Issue by Ristellise** [andrieslouw/imagesweserv#223]
Hello!

Been using images.weserv.nl for a caching proxy for my bot for certain images, recently I've noticed that discord now sends 403 errors, no matter what image I used. I suspect it might be a user agent problem. Is there anyone having the same problem?

**Comment by kleisauke** [comment]
I could reproduce this, it seems that Discord has blocked our User-Agent within their Cloudflare account. We're getting `error code: 1020` from all `*.discordapp.net` URLs.

If you are able to host this project yourself, you can use this to change the outgoing User-Agent within the nginx configuration:
```diff
--- a/ngx_conf/imagesweserv.conf
+++ b/ngx_conf/imagesweserv.conf
@@ -56,6 +56,7 @@ server {
     location / {
         resolver 8.8.8.8; # Use Google's open DNS server
         weserv_mode proxy; # Default
+        weserv_user_agent "Mozilla/5.0 (compatible; ImageFetcher/9.0; http://images.weserv.nl/)";
     }
 
     location /static {
```

Otherwise there's not much we can do for this. Please report this to Discord if it continues to be a problem.

**Comment by sudofox** [comment]
I tried setting the user agent this way but it does not seem to actually change the user agent. Tried restarting nginx, restarting the entire docker thing, etc, no dice. Any tips?

Edit: Editing the ngx_conf does not work. Directly editing /etc/nginx/imagesweserv.conf does work. I don't see any script or anything to 'deploy' the stuff from ngx_conf into /etc/nginx/ or any mentions of it in docs from looking for a minute or so.

**Comment by kleisauke** [comment]
Indeed, using the pre-built hosted image on [GitHub Container Registry](https://github.com/orgs/weserv/packages/container/package/images) (assuming that you're using Docker) requires changing `/etc/nginx/imagesweserv.conf` instead since the nginx configuration was 'deployed' during the image build.
https://github.com/weserv/images/blob/0d0c56dda1e827ab2924321668345de7e4e05210/docker/Dockerfile#L55-L56
https://github.com/weserv/images/blob/0d0c56dda1e827ab2924321668345de7e4e05210/docker/Dockerfile#L94-L95

The diff above assumes that the Docker image was built manually and that the Docker cache would be invalidated for this file (and thus 'redeployed' during the image rebuild).
https://github.com/weserv/images/tree/5.x/docker#manual-installation
