### ISSUE TITLE
Images.weserv.nl blocked in Russia

### ISSUE THREAD

**Issue by jetexe** [andrieslouw/imagesweserv#233]
Domain https://images.weserv.nl/ was blocked by [Roskomnadzor](https://rkn.gov.ru/eng/) in Russian Federation since 2020-05-19. Just for info

**Comment by andrieslouw** [comment]
_Let me repeat the statement I made on issue #158;_

And once again the Russia government is blocking large parts of the internet, including our service providers. It's the Russian version of the Chinese firewall, only even worse (as it's blocking completely, instead of monitoring and throttling). I hope you'll still be able to use GitHub, as it has been blocked multiple times in the past by Russia. 

Politics and internet seem to be an increasingly bad combination. I hope you'll be able to use VPN's or Tor. Cloudflare is increasing the support for Tor, maybe that will make some difference. However, I'm worried about Cloudflare being an U.S. company, with the U.S. also being in a really bad political climate.

I've looked into technologies to use on this service to bypass the Roskomnadzor blocks, but it's an uphill battle, which is hard to keep up with for us (costs, effort). Let's hope Russia will change it's mind, as the blocks are increasingly undermining day-to-day operations for everyone involved.

Please let your voice be heard during elections, and motivate others to do so. We're only able to provide the free and open services we'd like to, with the support of others doing the same.

To a better future 🥂

**Comment by e965** [comment]
@andrieslouw @kleisauke I see that you have implemented a mechanism for blocking access to images that have been entered in the Russian registry. Can you please write to Roskomnadzor by e-mail zapret-info@rkn.gov.ru with information about this? They must respond and remove the service from the registry.

**Comment by andrieslouw** [comment]
@e965 : Thank you for the hint, I wrote an e-mail, informing them of the steps taken. We indeed implementented CSAM-scanning based on hashes, through Cloudflare (details here: https://blog.cloudflare.com/the-csam-scanning-tool/ ).

**Comment by andrieslouw** [comment]
Our request has been taken in consideration by Roskomnadzor.

**Comment by e965** [comment]
As follows from the information from the [reestr.rublacklist.net](https://reestr.rublacklist.net/search/?q=images.weserv.nl), the service is completely unlocked in the Russian Federation.

![image](https://user-images.githubusercontent.com/18071040/109782459-bf024600-7c2a-11eb-960f-534c04b2f25d.png)

**Comment by andrieslouw** [comment]
Thank you for the feedback, I hope all users are able to reach the service again.

**Comment by jetexe** [comment]
All works! This is a good news for all of us!
