### ISSUE TITLE
Dropbox image do not open

### ISSUE THREAD

**Issue by felipe-ogestor** [andrieslouw/imagesweserv#237]
Hello people!

I'm having a problem using some images in the dropbox. Most are ok, but some are returning 404 (even if the image exists and is correct in the dropbox). 

Example: 
NOT WORKING: 
https://images.weserv.nl/?url=ssl%3Awww.dropbox.com%2Fs%2Fevzchi8siz8o01y%2F9c12c99d8934f78b0c2300122cf237ca.jpg%3Fraw%3D1
www.dropbox.com/s/evzchi8siz8o01y/9c12c99d8934f78b0c2300122cf237ca.jpg?raw=1

WORKING:
https://images.weserv.nl/?url=ssl%3Awww.dropbox.com%2Fs%2Fau3ecbvz6ynf8wg%2F059cb502e2a9c19a9a89c20be4fafec7.jpg%3Fraw%3D1
www.dropbox.com/s/au3ecbvz6ynf8wg/059cb502e2a9c19a9a89c20be4fafec7.jpg?raw=1

What can I be doing wrong?

**Comment by andrieslouw** [comment]
Strange, both links give 404 here, care to investigate @kleisauke ?

**Comment by kleisauke** [comment]
The problem was that Dropbox tried to redirect to a URI with a fragment identifier. These are reserved for client-side processing, and should be removed when performing HTTP(S) requests (RFC3986, Section 3.5).

This has been fixed with commit https://github.com/weserv/images/commit/e13c6e64e4625270603f13af0bf6bd8a13c7600c, which has just been rolled out to production. Thanks for reporting this!

**Comment by felipe-ogestor** [comment]
Yes, we noticed they were redirecting. We didn't understand why some images worked.

Anyway, thank you for the quick support!

Closing...
