### ISSUE TITLE
Resizing with fit=contain returns empty image

### ISSUE THREAD

**Issue by KimetaRWeber** [andrieslouw/imagesweserv#242]
We are currently running into the following problem: When trying to resize an image we get an empty image returned.

https://images.weserv.nl/?fit=contain&w=76&h=57&url=https%3A%2F%2Foffers.kimeta.de%2Fimages%2Flogos%2Flogo_franziskuswerk.gif

This only happens when fit is set to contain.

**Comment by kleisauke** [comment]
The problem was that the page height was set to an incorrect value for non-animated GIF and WebP images. In some cases, the image could become animated as a result.

This has been fixed with commit https://github.com/weserv/images/commit/11369e29449255ebfccbca535139d7c2a792bb3f, which has just been rolled out to production. Thanks for reporting this!
