### ISSUE TITLE
Invalid frames from animated gifs

### ISSUE THREAD

**Issue by fabian-emilius** [andrieslouw/imagesweserv#243]
When I try to resize the following animated gif, the resizer seems to read a wrong frame size and it looks like the image moves from top to bottom.

Source: https://cloudflare-ipfs.com/ipfs/QmSf3CvdGbKgfYTVpEkwDLLs1zsh1Tc2BJfb1UW4t4Mr4B
Resized: https://images.weserv.nl/?url=https://cloudflare-ipfs.com/ipfs/QmSf3CvdGbKgfYTVpEkwDLLs1zsh1Tc2BJfb1UW4t4Mr4B&h=370&w=370&fit=inside&we&q=50&n=-1&output=webp

**Comment by fabian-emilius** [comment]
Mmh I notice that it has been fixed in the live version but I still have this problem on my own server. Is there any branch with this fix?

**Comment by kleisauke** [comment]
Sorry for the delay, backlog was a bit large last week. This animated image reaches the limit of 256 pages, see:
```bash
$ vipsheader -f n-pages x.gif
300
```

I've increased it to 320 on the production server. But ideally in this case we should print an error instead of truncating the image (which does not work as you have noticed).

If you want to increase this limit on your server; try setting the `weserv_max_pages` directive in your nginx configuration. For example:
```nginx
weserv_max_pages 320;
```

**Comment by fabian-emilius** [comment]
Thanks for your answer. Is there a list with all of these options documented somewhere?

**Comment by kleisauke** [comment]
It's documented here: https://github.com/weserv/images/tree/5.x/ngx_conf.

**Comment by kleisauke** [comment]
Commit https://github.com/weserv/images/commit/8f6d213c8baada23eb92c810b837a21c2aeca7a0 should ensure that an error is returned instead of the image being truncated. Thanks for reporting this!
