### ISSUE TITLE
Border on white image on circle mask

### ISSUE THREAD

**Issue by Renato66** [andrieslouw/imagesweserv#245]
Original
![original](https://ui-avatars.com/api/?background=ffffff)
UiAvatars rounded param
![ui-avatars-rounded](https://images.weserv.nl/?w=44&h=44&url=https://ui-avatars.com/api/?background=ffffff&rounded=true)
WeServ mask circle
![weserv mask](https://images.weserv.nl/?mask=circle&w=44&h=44&url=https://ui-avatars.com/api/?background=ffffff)

**Comment by andrieslouw** [comment]
Looks like an alpha-channel anti-aliasing issue? Care to take a look @kleisauke ?

**Comment by kleisauke** [comment]
The `dest-in` operator needed unpremultiplied values and we specified an image that was premultiplied (not sure why I haven't noticed this earlier). This has been fixed with commit https://github.com/weserv/images/commit/ec7dacb970debe626056434f992e2a0843aa4398, which has just been rolled out to production. I now see:
![mask=circle](https://images.weserv.nl/?url=https://camo.githubusercontent.com/cc3a9ff47be9208a07626a7ef10c272543e5b578/68747470733a2f2f75692d617661746172732e636f6d2f6170692f3f6261636b67726f756e643d666666666666&mask=circle&output=png)
Thanks for reporting this!
