### ISSUE TITLE
How to configure Image resizing as Proxy Mode

### ISSUE THREAD

**Issue by sjahn90** [andrieslouw/imagesweserv#251]
We have origin server for image content. We want to use image resizing as proxy server.
I found how to resize image as on-the-fly.  [https://www.endpoint.com/blog/2016/05/25/caching-resizing-reverse-proxying-image-server-nginx](url)

 
 
So, we configure as follows. But we can't apply the image resizing. 

```
example environment
Origin server (IP: 1.1.1.1 as Nginx server) <-> Image proxy server (IP: 2.2.2.2) <-> Test Client (IP: 3.3.3.3)
```

Configuration of image proxy server are as follow.

```
http {
  ~~
  proxy_cache_path /usr/local/nginx/cache levels=1:2 keys_zone=mycache:10m max_size=100m;
  ~~
  server {
      listen 80;
      server_name _;

      location / {
        proxy_pass http://127.0.0.1:81;
        proxy_cache_valid 200 60m;
        proxy_cache mycache;
        proxy_cache_key "$proxy_host$uri$is_args$args";
      }
   }
  
 server {
      listen 81;
      server_name _;

      weserv on;

      location / {
        weserv_mode file;
        
        proxy_pass http://1.1.1.1:80;
      }
    }
}
```

When we run the follow command on test client, image resizing is not applied. Just original image is downloaded.

```
$ wget "http://2.2.2.2/test1.jpg?w=300&h=300" -O test1_300.jpg
```
 
 We want to know how to configure as proxy mode.

**Comment by kleisauke** [comment]
This is currently not supported. Both `proxy_pass` and `weserv_mode file` registers a content handler and each location block can only have one content handler at the same time. Therefore the `weserv_mode file` handler was overwritten by `proxy_pass`.

I had an attempt to support this combination, are you able to test commit https://github.com/weserv/images/commit/5a64718cb5eddaf47bd793e515b5df706c09a147 on the [`issue-251`](https://github.com/weserv/images/tree/issue-251) branch? You only have to make this adjustment in your nginx configuration:
```diff
@@ -18,10 +18,8 @@ http {
       listen 81;
       server_name _;
 
-      weserv on;
-
       location / {
-        weserv_mode file;
+        weserv filter;
         
         proxy_pass http://1.1.1.1:80;
       }
```

(I didn't include this commit on the main branch, because it's a breaking API change)

**Comment by sjahn90** [comment]
I'v tested with new branch. It works good. Thanks a lot.
Do you have a plan for including this commit on the main branch ?

**Comment by kleisauke** [comment]
Merged to the [`5.x`](https://github.com/weserv/images/tree/5.x) branch with commit https://github.com/weserv/images/commit/9ad5ba90a5fbfdee6c33f95f11f479b38d6968ec. Thanks for reporting this!
