### ISSUE TITLE
Support format converting of JPEG 2000 & JPEG XR

### ISSUE THREAD

**Issue by sjahn90** [andrieslouw/imagesweserv#256]
Depending on browser type, we want to change JPEG file to JPEG 2000, JPEG XR and WEBP.
WEBP is possible. 

Is it possible to change to JPEG 2000 or JPEG XR ? If no available, do yo have a plan to support JPEG 2000 & JPEG XR ?

**Comment by kleisauke** [comment]
Support for encoding to JPEG 2000 or JPEG-XR is currently not on our roadmap. I think the chances that these formats are widely supported is basically zero, given that JPEG 2000 is [supported solely by Safari](https://caniuse.com/jpeg2000) and JPEG-XR [was supported by none other than Internet Explorer 9+ (and Edge 12-18)](https://caniuse.com/jpegxr).

Also, due to Cloudflare's caching it's technically impossible to change the output depending on the type browser. Please use the `<picture>`-tag as explained in https://github.com/weserv/images/issues/214.

**Comment by sjahn90** [comment]
Thanks.
