### ISSUE TITLE
Self-hosting tips

### ISSUE THREAD

**Issue by raRaRa** [andrieslouw/imagesweserv#265]
Hey!

I was just wondering what would be the easiest way to self-host this service, without requiring Redis for rate limiting, etc. I would require some disk space for the service to download and process the files, correct?

It would be really cool if there was some easy way to set it up on a cloud server like Linode or Heroku, with all the requirements for it to run smoothly. I plan to have Cloudflare in front in order to cache requests to images.

**Comment by andrieslouw** [comment]
We do have a Docker image, but it should be pretty easy to run the code on any platform by inspecting our Docker image. Disk space is no specific requirement, everything could be done in memory (or /dev/shm). CloudFront or Cloudflare is advised indeed, our cache ratio is ~80% on Cloudflare for example.

Be advised that most of the code is CPU-bound and/or network-bound. The whole process is fetching image (network, download), applying the requested transformations (CPU, bit of RAM), and outputting to client (network, upload).

On our production servers the only disk I/O is due to code updates. We even keep most logfiles in RAM (/dev/shm), but you could also disable logs entirely.

So fast disk-access is no requirement, and if there is enough storage for OS + nginx + libvips, it should be fine.

**Comment by raRaRa** [comment]
I appreciate the detailed response @andrieslouw !

In theory I could run this service "serverless" using AWS Lambda with Cloudflare in front. That would be really cool. AWS Lambda recently launched support for containers, but it requires some changes to the code.

Just out of curiosity, do you run this service in the cloud, if not, what are the main reasons you run it yourself?

Thanks!

**Comment by andrieslouw** [comment]
The resources needed to run the free service are more than could be easily virtualized. We run multiple barebone servers, traffic is in the multiple Gbit/s on peaks, and we are able to fully saturate complete Ryzen-processors on all cores. Using dedicated boxes means we can do this extremely cheap; below €100/month cheap, while having the fastest response times. Downsides of using dedicated boxes (in Europe) is that visitors from e.g. Asia will have a small performance penalty. But we don't need any fancy global geo-balancing of traffic; round-robin is sufficient, and within Cloudflare's free tier. AWS could be interesting, but to calculate with our workload, on average: 120TB ingress per month, 50TB egress per month, ~8 compute cores, ~30GB RAM, 300 requests/sec, taking 500ms on average per request. This is with Cloudflare, without we would be doing ~1750TB egress traffic per month and 1500 requests/sec. Lambda would be around $6500 per month just for the compute/RAM (traffic is probably not included yet).

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
