### ISSUE TITLE
Focal point, why percentage and not focus point?

### ISSUE THREAD

**Issue by mortenholmgaard** [andrieslouw/imagesweserv#270]
I have started to use your image service with focalpoint.
https://images.weserv.nl/docs/crop.html#focal-point

We have a focus point selector for images in the administration, but after comparing the focus point selector preview to the images scaling results, I figured out that your service does not take the percentage set, as a focus point to make the most optimale image from but as a percentage of the possible cut frames of the image matching the aspect ratio.
To me that is a stange way to handle this - why would it not be handled as a focus point which to me at least is the most logical way to implement it, though I understand that this maybe was a faster implementation..

**Comment by kleisauke** [comment]
You're right, the implementation didn't take the original input width and height into account. Fixed with commit https://github.com/weserv/images/commit/b78d912bf2e4eb7f81f00a6889c73811cf5d32c6.

This commit also deprecates the confusing `&a=focal-x%-y%` percentage parameter, you can use `&a=focal&fpx=[x decimal]&fpy=[y decimal]` instead. The documentation has been updated to reflect this change:
https://images.weserv.nl/docs/crop.html#focal-point

Thanks for reporting this!

**Comment by mortenholmgaard** [comment]
@kleisauke Sounds good - I can't find any info about your deployment procedure? - I can see the documentation change is not live a least.

**Comment by kleisauke** [comment]
It's supposed to be live. There ought to be a pop-up when new content is available (i.e. when the service worker has installed an update), for example:
![Screenshot](https://user-images.githubusercontent.com/1254613/70602095-a6140c00-1c04-11ea-9848-962abdbe8fe0.png)
