### ISSUE TITLE
Animated gifs stopped working

### ISSUE THREAD

**Issue by Kuzmitch-hub** [andrieslouw/imagesweserv#274]
Hello,

I'm using your service for a long time with my forum and just found an issue couple of days ago. Every animated gif gives this error:

{"status":"error","code":400,"message":"libvips error: magicksave_buffer: libMagick error: NoDecodeDelegateForThisImageFormat `gif' @ error/blob.c/ImagesToBlob/1993\n"}

Examples: 

https://images.weserv.nl/?url=ssl:forum-img.guitarplayer.ru/2020/02/10/t78h.gif&output=gif&n=-1
Source: https://forum-img.guitarplayer.ru/2020/02/10/t78h.gif

https://images.weserv.nl/?url=s.fishki.net/upload/post/201412/18/1355700/gallery/1418875800_1469942070.gif&output=gif&n=-1
Source: http://s.fishki.net/upload/post/201412/18/1355700/gallery/1418875800_1469942070.gif

Can you please fix it? 

Thanks!
Michael

**Comment by kleisauke** [comment]
This seems to be caused by a recent ImageMagick soname bump (see https://github.com/weserv/rpms/commit/b74b78f2c3e362b09a567911edecba21c1c175d5), which caused the wrong `policy.xml` to be loaded. It should be fixed now.

I've modified our integration tests to prevent this from happening again, thanks for reporting this!

**Comment by Kuzmitch-hub** [comment]
No problem, I'm here to help :)
