### ISSUE TITLE
Filename can't be orientation options

### ISSUE THREAD

**Issue by errorID10TMC** [andrieslouw/imagesweserv#279]
When the filename is one of the orientation or some of the adjustment options it will change the images. An example of this using flip is below.

https://images.weserv.nl/?url=images.weserv.nl/lichtenstein.jpg&w=300&h=300&filename=flip

This image does have the filename of flip but the image is also flipped. This also happens with some filenames that include one of the options.

**Comment by kleisauke** [comment]
The problem was that the query string was parsed incorrectly. In some cases, key-value pairs could be misinterpreted as value-key pairs, as you discovered. This occurred for keys that were handled in the nginx module.

This has been fixed with commit https://github.com/weserv/images/commit/2bfc6bece48cf178a4e7b1f72bf06bf629e99847, which has just been rolled out to production. Thanks for reporting this!
