### ISSUE TITLE
The IP address request is too large and is blocked. How to unseal it

### ISSUE THREAD

**Issue by zhuang010203** [andrieslouw/imagesweserv#284]
The IP address request is too large and is blocked. How to unseal it

**Comment by andrieslouw** [comment]
Is your IP-address blocked, or is the URL blocked? Could you provide the exact error-message, or a screenshot?

**Comment by zhuang010203** [comment]
https://images.weserv.nl/?url=https://share.dmca.gripe/1PpGy1H1dd6kUU5c.png&default=www.z6z.xyz/index/public/images/downloaderrer.jpg

**Comment by zhuang010203** [comment]
![image](https://user-images.githubusercontent.com/59275452/116350674-eb020800-a824-11eb-8a4a-9e24fa1dae9e.png)

**Comment by zhuang010203** [comment]
Should IP be blocked? The computer can access the URL normally, but the server cannot import img

**Comment by zhuang010203** [comment]
Should IP be blocked? The local computer can access the URL normally, and the server cannot import img

**Comment by zhuang010203** [comment]
I used requests to simulate requests, all imgurls, pre caching

**Comment by zhuang010203** [comment]
Is IP blocked because of too many requests

**Comment by andrieslouw** [comment]
Our scripts did block a large number of .xyz domains due to too many requests, DMCA claims and pornography. It is hard for us to keep up with all these reports, so that's the reason they are blocked. Especially pornography is not allowed on the public API to prevent our service from getting blocked by others. Please use the source-code to host your own version in this case.

In addition, there are rate-limits on the public API, see: https://images.weserv.nl/news/2019/09/01/introducing-api-5/#improved-rate-limiter

**Comment by zhuang010203** [comment]
Pictures can only be considered sexy... How to judge pornography... I'll build one, thank you

**Comment by zhuang010203** [comment]
Pictures can only be considered sexy... How to judge pornographic, quite outrageous... I build an API, thank you

**Comment by andrieslouw** [comment]
Please do so, or else our service will be blocked in corporate firewalls etc. Let us know if you run into problems hosting the source code, many others are hosting themselves.
