### ISSUE TITLE
Blogger images 204 response

### ISSUE THREAD

**Issue by Merelybeing** [andrieslouw/imagesweserv#339]
Hi there, thanks a lot for your awesome work.
Recently, this project was applied to Blogger often 204 response and sometimes 404 response.
I found this to be similar to issue #332

Here is a screenshot of the request data when trying to load the image from Blogger:
![001](https://user-images.githubusercontent.com/24914557/162985401-27b593d2-accb-4416-b4b3-08df89798162.png)

And here is a screenshot of the request data when accessing the url same source url directly from the browser:
![002](https://user-images.githubusercontent.com/24914557/162985485-285c5011-727a-4436-a68a-022515e862e3.png)

**Comment by andrieslouw** [comment]
Due to multiple, and continuing, abuse of our service from many randomly generated cheap domains, we blocked all .cc .club .date .fun .pw .top .xxx .xyz domains on our public service. I'm really sorry for this, but the abuse was continuously using over 2 Gbit/s of our bandwidth, which we provide for free. Please consider changing domains to a normal TLD, or hosting the service yourself.

**Comment by Merelybeing** [comment]
Ok, finally know what's going on, thank you.
