### ISSUE TITLE
text on svg is vanished

### ISSUE THREAD

**Issue by VenomFate-619** [andrieslouw/imagesweserv#353]
**expected:-**

https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/0xca850e1deb88aef9579ee738493bc2bb1cbdf05978b968c337588b55ecb6528f/image

![image](https://user-images.githubusercontent.com/67755128/184071662-5e64f29f-e587-4422-aa42-599e54ca48af.png)

**output:-**

https://images.weserv.nl/?url=https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/0xca850e1deb88aef9579ee738493bc2bb1cbdf05978b968c337588b55ecb6528f/image

![image](https://user-images.githubusercontent.com/67755128/184071769-e03d821c-0a4a-47e1-a4ad-ae4a948bcf5b.png)

**content-type is wrong of this** 

![image](https://user-images.githubusercontent.com/67755128/184073424-6615de8c-cab1-4492-bf81-ebefb5eee7d5.png)

**Comment by VenomFate-619** [comment]
So , how to serve SVGs

**Comment by kleisauke** [comment]
SVG images are rasterized to pixels since they are not just images, but documents with full access to all HTML and JavaScript functions. It would be a security threat to serve SVG images as-is.

As for this particular image, you could try removing the `feDropShadow` filter and references, since it's currently unsupported by librsvg - see: https://gitlab.gnome.org/GNOME/librsvg/-/issues/743

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
