### ISSUE TITLE
Docs missing range of values for `sharpen` parameter

### ISSUE THREAD

**Issue by DH-at-PF** [andrieslouw/imagesweserv#357]
The example shows `3` but there is no range defined.

https://images.weserv.nl/docs/adjustment.html#sharpen

**Comment by kleisauke** [comment]
`sharp` needs to be in the range of 0.000001 - 10000.
https://github.com/weserv/images/blob/03684dc35801188ef12feed5219daf9da4b4c919/src/api/processors/sharpen.cpp#L13-L21

And `sharpf` and `sharpj` needs to be in the range of 0 - 10000.
https://github.com/weserv/images/blob/03684dc35801188ef12feed5219daf9da4b4c919/src/api/processors/sharpen.cpp#L35-L53

Though, the last two could possibly be increased to a million (1×10<sup>6</sup>), since libvips allows that.
https://github.com/libvips/libvips/blob/e24cee4e224af32d85ab2fd52f57c2482cc87d9c/libvips/convolution/sharpen.c#L356-L368

I'll look into mentioning this on the website.

**Comment by kleisauke** [comment]
Commit a82438c8d3fdb124f3746af74d77ff42a15aaddd updates the maximum values of the sharpen operation, documentation still needs to be updated.

**Comment by kleisauke** [comment]
Documentation has been updated.
https://wsrv.nl/docs/adjustment.html#sharpen
