### ISSUE TITLE
php

### ISSUE THREAD

**Issue by degarb** [andrieslouw/imagesweserv#368]
I spent about 5 hours failing to install docker on windows.   I do have a php webserver running on windows.  

Can I get weserv to run on windows?

**Comment by andrieslouw** [comment]
We stopped using PHP some years ago, nowadays this whole project is written in C++

Would advise you to use docker. But if you really want, we still have a copy of the PHP source code here: https://github.com/weserv/images/tree/3.x

Be careful, this is older code, and features may be different, missing or slower.

**Comment by leonardhamana** [comment]
Yes, you can run a web server on Windows. There are several web servers that can run on Windows, including:

Apache HTTP Server: a popular open-source web server that supports a variety of operating systems, including Windows.

Nginx: a lightweight and high-performance web server that can run on Windows.

Microsoft IIS (Internet Information Services): a web server built into Windows that is widely used in enterprise environments.

To get started, you can choose one of these web servers and follow the installation instructions. Once the web server is installed, you can configure it to serve PHP scripts by installing PHP and configuring the web server to use the PHP module.

If you already have a PHP web server running on Windows, you can use that to serve your website. Just make sure that the web server is configured correctly and that the necessary PHP modules are installed.
**To use Docker with a PHP web server, you can follow these general steps:**

Create a Dockerfile: This is a file that describes the environment and dependencies required for your PHP web server to run. You can start with a pre-built PHP image and then add any additional dependencies required for your web server.

Build the Docker image: Use the docker build command to build the Docker image using the Dockerfile.

Run the Docker container: Use the docker run command to start the container and run your PHP web server inside the container. Make sure to specify the correct port mappings so that you can access the web server from your local machine.

Test the web server: Open a web browser and navigate to the IP address of your Docker host and the port specified in the port mapping to verify that the web server is running.
