### ISSUE TITLE
PDF's no longer accepted

### ISSUE THREAD

**Issue by jere-co** [andrieslouw/imagesweserv#396]
I've been using this heavily to generate preview images of PDF documents, which worked great until recently. 

Earlier, this worked perfectly: 
```TS
`https://wsrv.nl/?url=${URL_TO_PDF_DOCUMENT}&output=jpg`;
```

But now is giving: 
```JSON
{"status":"error","code":404,"message":"Invalid or unsupported image format. Is it a valid image?"}
```

I couldn't find any reason why this no longer works. Any thoughts?

**Comment by kleisauke** [comment]
This seems to be caused by a configuration error after the update to libvips 8.15.0-rc1 (see https://github.com/weserv/rpms/commit/c9c2a9422096c213ceafe23c962d4f1e6aec13dd), which prevented the dynamic modules required for this format from being loaded. It should be fixed now.

I've modified our integration tests to prevent this from happening again, thanks for reporting this!

**Comment by jere-co** [comment]
Awesome! Thank you for the quick fix!
