### ISSUE TITLE
&shape=circle not working?

### ISSUE THREAD

**Issue by Phyxsius21** [andrieslouw/imagesweserv#85]
Hey!
I'm trying to change the shape of [an image](https://images.weserv.nl/?url=avatar.leagueoflegends.com/summonerid/na/5908.png&shape=circle), but atm it's not working, although it was some hours ago.
Is there any problem on your end or it's me doing something wrong?

**Comment by kleisauke** [comment]
It seems that this is a bug in our old script. Cropping to a circle without specifying the width (`&w=`) or height (`&h=`) is broken in that script. For example, this is fixable if you specify only the width:
https://images.weserv.nl/?url=avatar.leagueoflegends.com/summonerid/na/5908.png&w=128&shape=circle

If you were wondering why it did work some hours ago; we’re currently doing some tests with a small number of requests (A/B-testing) to our newest API (version 3) where this bug is fixed in. Sorry for any inconvenience caused.

**Comment by andrieslouw** [comment]
As stated, A/B-testing caused some issues here, old versions need both &h= and &w=, new versions work well with only one parameter given. It should be solved now. I'll close this issue.
