### ISSUE TITLE
Discoloration and unexpected transparency using output=WebP

### ISSUE THREAD

**Issue by leongersen** [andrieslouw/imagesweserv#93]
Using the WebP output method, I'm seeing odd results on some images, and I can't narrow down why. Here is an example:

Output as JPEG (ok):
https://images.weserv.nl/?il&t=squaredown&w=640&h=480&url=s3-eu-west-1.amazonaws.com%2Fair-photos%2F0000107357%2Ftarget-2048-60.jpg&q=40

The same image, output as WebP (bad):
https://images.weserv.nl/?il&t=squaredown&w=640&h=480&url=s3-eu-west-1.amazonaws.com%2Fair-photos%2F0000107357%2Ftarget-2048-60.jpg&q=40&output=webp

I've tried removing all other parameters: they're not the cause.

**Comment by kleisauke** [comment]
Thanks for reporting! This bug is due to incorrect interpretation of color profiles.

The linked picture has no color-space metadata (it looks like a CMYK image) and no embedded color profile, which causes an incorrect WebP output (unexpected transparency/desaturation).

This issue has been fixed in https://github.com/andrieslouw/imagesweserv/commit/e648861ae869ed9f34b119380db6f5eb0641389b which supports CMYK input images without an embedded profile. 
If there's an embedded profile on the input image, we'll now always attempt to use it to convert to the device-independent sRGB color space.

If you want, you can test this fix on our test environment:
https://t0.nl/?url=s3-eu-west-1.amazonaws.com%2Fair-photos%2F0000107357%2Ftarget-2048-60.jpg&t=squaredown&w=640&h=480&output=webp

I'll report back when this fix is implemented on the production server.

**Comment by leongersen** [comment]
Ah, great. Thanks for investigating! I'm assuming I'll have to bust cache on these images when the fix rolls out?

**Comment by kleisauke** [comment]
Fix has been rolled out to production. Cache for some images still needs to be invalidated. 

If you want, you can send us an [email](mailto:admin@weserv.nl) with the images that are affected by this bug and need to be purged from cache.

**Comment by leongersen** [comment]
I had no real way of finding all affected images, so I waited out the cache period before re-deploying WebP.  

Thanks for fixing this!
