### ISSUE TITLE
Is svg+xml supported?

### ISSUE THREAD

**Issue by adin234** [andrieslouw/imagesweserv#95]
can this proxy an svg+xml?

`http://svgshare.com/i/1de.svg`
![GitHub Logo](http://svgshare.com/i/1de.svg)

`https://images.weserv.nl/?url=svgshare.com/i/1de.svg`
![GitHub Logo](https://images.weserv.nl/?url=svgshare.com/i/1de.svg)

**Comment by kleisauke** [comment]
SVG images are supported, it will be loaded through `librsvg`.

This particular SVG image doesn't output correctly because negative `stroke-dashoffset` values are not supported by `librsvg` (see [rsvg-styles.c#L853-L854](https://github.com/GNOME/librsvg/blob/81bbfe8e5a9815bda2f63d694900021a3c3d8a80/rsvg-styles.c#L853-L854)).

I've tried to fix your SVG image:
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120" viewBox="0 0 120 120">
  <circle cx="60" cy="60" r="54" fill="none" stroke="#F77A52" stroke-width="12" stroke-dasharray="250" transform="rotate(90 60 60)"/>
  <circle cx="60" cy="60" r="42" fill="none" stroke="#E00" stroke-width="12" stroke-dasharray="200" transform="rotate(90 60 60)" />
</svg>
```
(uploaded [here](https://t0.nl/95.svg))

Output:
[![image](https://cloud.githubusercontent.com/assets/12746591/26255202/24c4a236-3cb9-11e7-8411-fe16d0ca4896.png)](https://images.weserv.nl/?url=t0.nl/95.svg)

**Comment by adin234** [comment]
thanks for the help!
