### ISSUE TITLE
[Question] invalid url image

### ISSUE THREAD

**Issue by Kikobeats** [andrieslouw/imagesweserv#99]
Hello,

I'm trying to resize an image from Twitter CDN:

```
https://pbs.twimg.com/media/DFShydiXsAE0APy.jpg
```

but imagesweserv says it is not an image

```
https://images.weserv.nl/?url=https://pbs.twimg.com/media/DFShydiXsAE0APy.jpg
Error 404: Server couldn't parse the ?url= that you were looking for, because it isn't a valid url.
```

Any idea what is happening?

**Comment by Kikobeats** [comment]
My fault; it is working removing protocol

```
https://images.weserv.nl/?url=pbs.twimg.com/media/DFShydiXsAE0APy.jpg
```

Probably could be easy add this functionality internally and remove protocol from the URL if it is present 🤔

**Comment by andrieslouw** [comment]
Related issue https://github.com/andrieslouw/imagesweserv/issues/19

Also; we won't strip nor accept http(s):// in the ?url= because it's considered bad practice to do so. UBB-parsers frequently fail on the double http:// in an [img]-tag; this has caused numerous issues in the past. So please remove the http(s):// part yourself to be consistent. (In addition; to force https-fetching, use ssl: in front, so ?url=ssl:www.google.com/etc )

**Comment by Kikobeats** [comment]
thanks 😄
